name: PHP CI (No Composer)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Download PHPUnit
        run: |
          wget https://phar.phpunit.de/phpunit-10.phar
          chmod +x phpunit-10.phar
          php phpunit-10.phar --version

      - name: PHP Lint
        run: |
          find . -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 php -l

      - name: Run PHPUnit tests
        run: php phpunit-10.phar --testdox --colors=always

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_PROJECT }}
        with:
          args: >
            -Dsonar.projectKey=Ismail-khlif_miniprojet-DevOps
            -Dsonar.organization=ismail-khlif
            -Dsonar.sources=.
            -Dsonar.tests=tests
            -Dsonar.language=php

      - name: SonarCloud Report Link
        run: |
          echo "SONARCLOUD REPORT"
          echo ""
          echo "Issues:"
          echo "https://sonarcloud.io/project/issues?id=Ismail-khlif_miniprojet-DevOps"
          echo ""
          echo "Project Overview:"
          echo "https://sonarcloud.io/project/overview?id=Ismail-khlif_miniprojet-DevOps"
